### ISSUE TITLE
chef-client 13 now sets amazon linux machines platform_family to amazon instead of rhel

### ISSUE THREAD

**Issue by Stromweld** [chef-cookbooks/cron#101]
### Cookbook version
4.1.0

### Chef-client version
13.0.113

### Platform Details
Amazon linux 2016.09 running in AWS cloud

### Scenario:
converge with cron cookbook enabled

### Steps to Reproduce:
create an amazon linux instance with cron::default in it's runlist

### Expected Result:
convergence

### Actual Result:
chef-client run errors due to wrong service name on service resource.

**Comment by tas50** [comment]
Released. Thanks

**Comment by Stromweld** [comment]
Thanks for the quick turn around and push to supermarket.
