### ISSUE TITLE
CIS friendly permissions

### ISSUE THREAD

**Issue by mengesb** [chef-cookbooks/cron#106]
### Cookbook version
5.0.1

### Chef-client version
13.6.4

### Platform Details
RHEL 7.4.1708

### Scenario:
Use cron cookbook in CIS hardened systems

### Steps to Reproduce:
Use any cookbook with CRON as a dependency or directly on a CIS system

### Expected Result:
Allow permissions of various cron elements to be set (not reset) CIS requirements

### Actual Result:
Enforces prescribed permissions

---

Per CIS guidelines, the following rules are violated in this cookbook:
- 5.1.2     Ensure permissions on /etc/crontab are configured (Scored)     recommended    chown root:root /etc/crontab; chmod og-rwx /etc/crontab
- 5.1.3     Ensure permissions on /etc/cron.hourly are configured (Scored)     recommended    chown root:root /etc/cron.hourly ; chmod og-rwx /etc/cron.hourly
- 5.1.4     Ensure permissions on /etc/cron.daily are configured (Scored)     recommended    chown root:root /etc/cron.daily ; chmod og-rwx /etc/cron.daily
- 5.1.5    Ensure permissions on /etc/cron.weekly are configured (Scored)     recommended    chown root:root /etc/cron.weekly ; chmod og-rwx /etc/cron.weekly
- 5.1.6     Ensure permissions on /etc/cron.monthly are configured (Scored)     recommended    chown root:root /etc/cron.monthly ; chmod og-rwx /etc/cron.monthly
- 5.1.7    Ensure permissions on /etc/cron.d are configured (Scored)     recommended    chown root:root /etc/cron.d ; chmod og-rwx /etc/cron.d

Allowing a permissions set for the above resources would allow the system to be compliant and allow cookbook usage in CIS scenarios

**Comment by tas50** [comment]
I've updated the cron files to all default to 0600. Thanks for the heads up
