### ISSUE TITLE
.DS_Store checked into 6.1.1 supermarket source

### ISSUE THREAD

**Issue by kyleian** [chef-cookbooks/cron#115]
Hello,

After the same fashion as this issue: https://github.com/chef-cookbooks/cron/issues/68

I'm finding that a .DS_Store file is present in the supermarket source for cron cookbook version 6.1.1, prohibiting successful berks upload executions (  bundle exec berks upload --except=integration )

```kyleian-mbp1:cron kyle.ian$ pwd
/Users/kyle.ian/Downloads/cron 
kyleian-mbp1:cron kyle.ian$ ls -haltr
total 72
-rw-r--r--@   1 kyle.ian  staff   5.1K May 11 19:19 metadata.json
-rw-r--r--@   1 kyle.ian  staff   4.0K May 11 19:19 README.md
-rw-r--r--@   1 kyle.ian  staff   111B May 11 19:19 CONTRIBUTING.md
-rw-r--r--@   1 kyle.ian  staff   7.2K May 11 19:19 CHANGELOG.md
drwxr-xr-x@   4 kyle.ian  staff   136B Jul 13 17:48 templates
drwxr-xr-x@   4 kyle.ian  staff   136B Jul 13 17:48 resources
drwxr-xr-x@   3 kyle.ian  staff   102B Jul 13 17:48 recipes
drwxr-xr-x@   3 kyle.ian  staff   102B Jul 13 17:48 libraries
drwxr-xr-x@   3 kyle.ian  staff   102B Jul 13 17:48 attributes
drwx------+ 368 kyle.ian  staff    12K Jul 13 17:48 ..
drwxr-xr-x@  12 kyle.ian  staff   408B Jul 13 17:48 .
-rw-r--r--@   1 kyle.ian  staff   6.0K Jul 13 17:48 .DS_Store
```

chef --version:

Chef Development Kit Version: 2.2.1
chef-client version: 13.3.42
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.35.1

**Comment by tas50** [comment]
This is resolved in later releases. Sorry for the trouble
