### ISSUE TITLE
Validation doesn't accept commas or lists of parameters

### ISSUE THREAD

**Issue by martinb3** [chef-cookbooks/cron#37]
While the README says:

```
minute, hour, day, month, weekday - schedule your cron job. These correspond exactly to their equivalents in the crontab file. All default to "*".
```

In actual crontab files, I can do something like `1,2,3,4` in the hour field. This cookbook does not accept that syntax, so it's not an exact equivalence. Just wanted to call that out in case someone else runs into it.

**Comment by iRonin** [comment]
Is it working yet?

**Comment by tas50** [comment]
We reworked all our validation logic in the last year. If this is still an issue feel free to open it back up.
