### ISSUE TITLE
Provider does not create cron.d files when run from a ruby_block that it self was run as a :delayed notification

### ISSUE THREAD

**Issue by alexderz** [chef-cookbooks/cron#53]
If the CronD resource is created and run from a *ruby_block* that was itself run as a *:delayed* notification from yet another resource, then the internal *template* and *file* providers (for *:create* and *:delete* actions, respectively) never trigger. 

Chef-client reports the cron_d resource as up to date, but there is no corresponding /etc/cron.d file. This is because the *update_by_last_action* is false as the internal *file* or *template* resource has not yet run.

Attaching a simple fix via pull request shortly.

**Comment by tas50** [comment]
This shouldn't be necessary now that we use inline resources in Chef 11+.  If this is still an issue do let me know.
