### ISSUE TITLE
Service enable - no implicit conversion of false into Array

### ISSUE THREAD

**Issue by erkolson** [chef-cookbooks/cron#59]
I get this error about half the time I build a new box.  (chef-client 12.4.1, centos7).  I am unable to recreate in test kitchen.

```
 * yum_package[cron] action install (up to date)
 * service[cron] action enable
================================================================================
   Error executing action `enable` on resource 'service[cron]'
   ================================================================================

   TypeError
   ---------
   no implicit conversion of false into Array

   Resource Declaration:
   ---------------------
   # In /var/chef/cache/cookbooks/cron/recipes/default.rb

    31: service 'cron' do
    32:   service_name 'crond' if platform_family?('rhel', 'fedora')
    33:   service_name 'vixie-cron' if platform_family?('gentoo')
    34:   action [:enable, :start]
    35: end

   Compiled Resource:
   ------------------
   # Declared in /var/chef/cache/cookbooks/cron/recipes/default.rb:31:in `from_file'

   service("cron") do
     action [:enable, :start]
     supports {:restart=>false, :reload=>false, :status=>false}
     retries 0
     retry_delay 2
     default_guard_interpreter :default
     service_name "crond"
     pattern "cron"
     declared_type :service
     cookbook_name "cron"
     recipe_name "default"
   end
```

**Comment by alexderz** [comment]
Is there a stack trace along with the error? Any extra output when running the client in debug mode? 

Strange that it happens only sometimes.

**Comment by erkolson** [comment]
It appears this is actually an issue in chef, not the cron cookbook!

This hit me again today with a completely different service.  It was in test kitchen so I was able to view the stack trace.  It points to line 134 here - https://github.com/chef/chef/blob/master/lib/chef/platform/service_helpers.rb

The extract_systemd_services shell_out apparently fails causing it to return the false from line 129, which produces the unable to convert boolean to array error when trying to add the two arrays together on line 134.

**Comment by alexderz** [comment]
Yea, that implies that `systemctl list-unit-files` exits with an error status.

**Comment by Blasterdick** [comment]
+1, kitchen, centos7. And, it seems like I can't override `default['cron']['service_name']` with `node.force_override['cron']['service_name'] = "crond"`, like I can do for `default['cron']['package_name']`

**Comment by tas50** [comment]
We've reworked the service block in the current version and I'm not seeing a similar error on any platform. Feel free to open this back up if you're still seeing the issue.
