### ISSUE TITLE
Convert manage definition to a LWRP

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/cron#62]
This gives us nice new functionality

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.

**Comment by iennae** [comment]
Would a manage resource as implemented as the definition file make sense? Right now it is based on individual users. Would a single resource that took the input of users that either were allow or denied make sense? I implemented this using Chef::Util::FileEdit's insert_line_if_no_match function, but after I did it realized that maybe a new resource is needed here.

**Comment by tas50** [comment]
Converted with full backwards compatibility by using the accumulator pattern
