### ISSUE TITLE
:delete action requires a command resource attr

### ISSUE THREAD

**Issue by patcon** [chef-cookbooks/cron#67]
Ran into this, so thought I'd open a stub. Not critical to my uses, so likely not working on a PR myself unfortunately

**Comment by tas50** [comment]
This was fixed in the 1.7.2 release today https://github.com/chef-cookbooks/cron/commit/39211d26776627b316b22efcb1b8733fa84c56a9

**Comment by patcon** [comment]
:+1: haha wow. what timing for my first ever issue on this project. Thanks for the heads up :)
