### ISSUE TITLE
.DS_Store file in supermarket source for version 1.7.2

### ISSUE THREAD

**Issue by veetow** [chef-cookbooks/cron#68]
Hello,

In `cron-1.7.2` there is a  file at `templates/.DS_Store` which prevents the cookbook from being uploaded into Chef Server via `berks upload`.  I don't see that file here in the github repo, so I'm not sure how it's getting introduced but I thought I should report it in any case.

Thanks,
Vito

**Comment by tas50** [comment]
I've re-released it with the ds store files nuked.  I'm a bit confused on how it got in there in the first place.  Stove should remove those before pushing to Supermarket.
