### ISSUE TITLE
* is not valid value for validate_numeric

### ISSUE THREAD

**Issue by sebfek** [chef-cookbooks/cron#71]
Just for information:

    ==> default:   Default value "*" is invalid for property minute of resource cron_d. In Chef 13 this will become an error: undefined method `validate_numeric' for #<Class:0x00000003291820>. at 1 location:
    ==> default:     - /var/chef/cache/cookbooks/cron/resources/d.rb:27:in `class_from_file'
    ==> default:   Default value "*" is invalid for property hour of resource cron_d. In Chef 13 this will become an error: undefined method `validate_numeric' for #<Class:0x00000003291820>. at 1 location:
    ==> default:     - /var/chef/cache/cookbooks/cron/resources/d.rb:28:in `class_from_file'
    ==> default:   Default value "*" is invalid for property day of resource cron_d. In Chef 13 this will become an error: undefined method `validate_numeric' for #<Class:0x00000003291820>. at 1 location:
    ==> default:     - /var/chef/cache/cookbooks/cron/resources/d.rb:29:in `class_from_file'
    ==> default:   Default value "*" is invalid for property month of resource cron_d. In Chef 13 this will become an error: undefined method `validate_month' for #<Class:0x00000003291820>. at 1 location:
    ==> default:     - /var/chef/cache/cookbooks/cron/resources/d.rb:30:in `class_from_file'
    ==> default:   Default value "*" is invalid for property weekday of resource cron_d. In Chef 13 this will become an error: undefined method `validate_dow' for #<Class:0x00000003291820>. at 1 location:
    ==> default:     - /var/chef/cache/cookbooks/cron/resources/d.rb:31:in `class_from_file'

**Comment by wedtm** [comment]
+1 on this

**Comment by andrewheald** [comment]
Yes, given that cron is pulled in by chef-client, I'm a definite +1 on this one. I might, if time permits, submit a patch for this, but I'm not 100% sure I understand the underlying issue as yet.

**Comment by sumit-goel** [comment]
+1

I am getting the same messages with chef-client 12.7.2

```
Deprecated features used!
  Default value "*" is invalid for property minute of resource cron_d. In Chef 13 this will become an error: undefined method `validate_numeric' for #<Class:0x000000057fc448>. at 1 location:
    - /var/cache/chef/cookbooks/cron/resources/d.rb:27:in `class_from_file'
  Default value "*" is invalid for property hour of resource cron_d. In Chef 13 this will become an error: undefined method `validate_numeric' for #<Class:0x000000057fc448>. at 1 location:
    - /var/cache/chef/cookbooks/cron/resources/d.rb:28:in `class_from_file'
  Default value "*" is invalid for property day of resource cron_d. In Chef 13 this will become an error: undefined method `validate_numeric' for #<Class:0x000000057fc448>. at 1 location:
    - /var/cache/chef/cookbooks/cron/resources/d.rb:29:in `class_from_file'
  Default value "*" is invalid for property month of resource cron_d. In Chef 13 this will become an error: undefined method `validate_month' for #<Class:0x000000057fc448>. at 1 location:
    - /var/cache/chef/cookbooks/cron/resources/d.rb:30:in `class_from_file'
  Default value "*" is invalid for property weekday of resource cron_d. In Chef 13 this will become an error: undefined method `validate_dow' for #<Class:0x000000057fc448>. at 1 location:
    - /var/cache/chef/cookbooks/cron/resources/d.rb:31:in `class_from_file'
```

**Comment by dainiax** [comment]
+1

**Comment by apeschel** [comment]
:+1:

**Comment by pkang** [comment]
+1

**Comment by vincentaubert** [comment]
+1

**Comment by chilicheech** [comment]
+1

**Comment by ricksebak** [comment]
+1

And in case my usage is any different than others, I'm doing:
`minute '*/15'`

**Comment by binlialfie** [comment]
+1

**Comment by tas50** [comment]
This is being looked into.  I'm locking the thread at this point since the +1s aren't providing more useful information.
