### ISSUE TITLE
Add "RANDOM_DELAY" option.

### ISSUE THREAD

**Issue by nkadel-skyhook** [chef-cookbooks/cron#85]
### Cookbook version
  cron (1.7.6)

### Chef-client version
[Version of chef-client in your environment]
  chef-client version: 12.10.24

### Platform Details
CentOS 6 and CentOS 7

### Scenario:
Randomize start times for /etc/cron.d/ managed tasks, using "RANDOM_DELAY" feature of contemporary versions of "cronie"

### Steps to Reproduce:
No options to publish or manage "RANDOM_DELAY" features are in templates/default/cron.d.erb.

### Expected Result:
Setting RANDOM_DELAY as an LWRP attribute should activate features documented at http://man7.org/linux/man-pages/man5/crontab.5.html

### Actual Result:
Feature is unavailable.

**Comment by nkadel-skyhook** [comment]
I've added a pull request to provide this, https://github.com/chef-cookbooks/cron/pull/88 .

**Comment by nkadel-skyhook** [comment]
I see the merge completed, thank you!

**Comment by mark-from-usds** [comment]
Is this actually resolved? Does random_delay also need to be added to https://github.com/chef-cookbooks/cron/blob/master/resources/d.rb ? Right now I get "undefined method" when I try to use it.
