### ISSUE TITLE
empty or nil environment values cause cron errors

### ISSUE THREAD

**Issue by grosser** [chef-cookbooks/cron#86]
### Cookbook version
1.7 ... but same code in latest https://github.com/chef-cookbooks/cron/blob/2ca55eb02a5425d780bb41aae38ecfa3f7d126e0/templates/default/cron.d.erb#L14

### Chef-client version
latest

### Platform Details
Ubuntu 12.04.5 LTS

### Scenario:
use empty or nil env vars or env var with \n

### Steps to Reproduce:
`environment foo: "", bar: nil`

### Expected Result:
```
foo=""
bar=""
```

### Actual Result:
```
foo=
bar=
...

which results in

```
Error: bad minute; while reading /etc/cron.d/env_test
```

**Comment by tas50** [comment]
Fixed when we merge #87
