### ISSUE TITLE
No metadata.rb or metadata.json found for cookbook cron

### ISSUE THREAD

**Issue by Bdelmedico** [chef-cookbooks/cron#89]
### Cookbook version
cron version 4.0.0.

### Chef-client version
Chef Client, version 12.19.33

### Platform Details
ubuntu 14.04

### Scenario:
install cron

### Steps to Reproduce:
# knife cookbook site install cron
Installing cron to /root/code/chef/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-cron) exists, switching to it.
Downloading cron from Supermarket at version 4.0.0 to /root/code/chef/cookbooks/cron.tar.gz
Cookbook saved: /root/code/chef/cookbooks/cron.tar.gz
Removing pre-existing version.
Uncompressing cron version 4.0.0.
Removing downloaded tarball
No changes made to cron
Checking out the master branch.
ERROR: Chef::Exceptions::MetadataNotFound: No metadata.rb or metadata.json found for cookbook cron in /root/code/chef/cookbooks

### Actual Result:
ERROR: Chef::Exceptions::MetadataNotFound: No metadata.rb or metadata.json found for cookbook cron in /root/code/chef/cookbooks

**Comment by chasebolt** [comment]
I've had this happen in the past for a cookbook I deployed to supermarket. It's as if supermarket didn't generate the metadata.json when I uploaded it. Had to re-upload to supermarket to fix it.

**Comment by tas50** [comment]
I'm about to push a new cookbook release. Closing this out now
