### ISSUE TITLE
cron_d month option not accepting integer.

### ISSUE THREAD

**Issue by Stromweld** [chef-cookbooks/cron#90]
### Cookbook version
4.0.0

### Chef-client version
12.19.36

### Platform Details
CentOS 6.8 running on AWS

### Scenario:
using auto-patch cookbook to set cron job for monthly patches. auot-patch::linux recipe uses cron_d resource to create a cron job and fails when trying to set month option to 3.

### Steps to Reproduce:
setting month option for cron_d to 3

### Expected Result:
cron job for march gets created. 

### Actual Result:
fails with error Option month's value 3 is not a month spec. It does work with "mar"

172.21.16.233 [2017-03-08T15:19:49-05:00] INFO: Auto patch scheduled for 2017-03-21 at 4:0
172.21.16.233   
172.21.16.233   ================================================================================
172.21.16.233   Recipe Compile Error in /var/chef/cache/cookbooks/role-base-linux-nativex/recipes/default.rb
172.21.16.233   ================================================================================
172.21.16.233   
172.21.16.233   Chef::Exceptions::ValidationFailed
172.21.16.233   ----------------------------------
172.21.16.233   Option month's value tue should be a valid month spec!
172.21.16.233   
172.21.16.233   Cookbook Trace:
172.21.16.233   ---------------
172.21.16.233     /var/chef/cache/cookbooks/auto-patch/recipes/default.rb:99:in `block in from_file'
172.21.16.233     /var/chef/cache/cookbooks/auto-patch/recipes/default.rb:94:in `from_file'
172.21.16.233     /var/chef/cache/cookbooks/autopatch-nativex/recipes/linux.rb:94:in `from_file'
172.21.16.233     /var/chef/cache/cookbooks/autopatch-nativex/recipes/default.rb:18:in `from_file'
172.21.16.233     /var/chef/cache/cookbooks/role-base-linux-nativex/recipes/default.rb:171:in `from_file'
172.21.16.233   
172.21.16.233   Relevant File Content:
172.21.16.233   ----------------------
172.21.16.233   /var/chef/cache/cookbooks/auto-patch/recipes/default.rb:
172.21.16.233   
172.21.16.233    92:  end
172.21.16.233    93:  
172.21.16.233    94:  cron_d 'auto-patch' do
172.21.16.233    95:    hour node['auto-patch']['hour']
172.21.16.233    96:    minute node['auto-patch']['minute']
172.21.16.233    97:    weekday node['auto-patch']['weekday']
172.21.16.233    98:    day node['auto-patch']['day']
172.21.16.233    99>>   month 'tue'
172.21.16.233   100:    command '/usr/local/sbin/auto-patch'
172.21.16.233   101:    action :delete if node['auto-patch']['disable']
172.21.16.233   102:  end
172.21.16.233   103:  
172.21.16.233   
172.21.16.233   Platform:
172.21.16.233   ---------
172.21.16.233   x86_64-linux
172.21.16.233   
172.21.16.233   
172.21.16.233   Running handlers:
172.21.16.233 [2017-03-08T15:19:49-05:00] ERROR: Running exception handlers
172.21.16.233   Running handlers complete
172.21.16.233 [2017-03-08T15:19:49-05:00] ERROR: Exception handlers complete
172.21.16.233   Chef Client failed. 2 resources updated in 07 seconds
172.21.16.233 [2017-03-08T15:19:49-05:00] INFO: Sending resource update report (run-id: e794d804-909c-4ad3-ad59-5f73975b1bfe)
172.21.16.233 [2017-03-08T15:19:49-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
172.21.16.233 [2017-03-08T15:19:49-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
172.21.16.233 [2017-03-08T15:19:49-05:00] ERROR: Option month's value tue should be a valid month spec!
172.21.16.233 [2017-03-08T15:19:49-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by Stromweld** [comment]
in testing it does accept numeric strings but not integers.

**Comment by eherot** [comment]
Pretty sure this is a dup of #74

**Comment by Stromweld** [comment]
I wouldn't say duplicate. The cron_d resource or lwrp used to accept individual integers like 3 for march. Now it only accepts "3" as a string and not integer.

**Comment by Stromweld** [comment]
Sorry my last post was while I was on my phone and from the description they are different but your pull request does fix this issue as well. Thanks.

**Comment by eherot** [comment]
Both a result of validating Fixnums incorrectly ;-)

**Comment by eherot** [comment]
The problem was introduced, it seems, by some overzealous application of otherwise well-meaning [Cookstyle fixes](https://github.com/chef-cookbooks/cron/commit/3af4ce7af915640453f57cbfffe4113113eeff10) (possibly because of a bug in CS at the time).

**Comment by tas50** [comment]
Fixed on master
