### ISSUE TITLE
Release v4.1.0 not tagged

### ISSUE THREAD

**Issue by madwort** [chef-cookbooks/cron#97]
### Cookbook version
4.1.0

### Scenario:
Would like to use v4.1.0 which I think removes Chef 13 deprecation warnings, there's a commit for v4.1.0 in master but no tag/release on github so we have to manually specify commit reference in order to use it. Could you hit the release button, please? Thanks!

**Comment by tas50** [comment]
Looks like my stove push failed. I've pushed again

**Comment by madwort** [comment]
Ah, great stuff, thanks!
